// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egbmulrdrsmhxnogompo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnYm11bHJkcnNtaHhub2dvbXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDY4MDMsImV4cCI6MjA2ODIyMjgwM30.OJJKhvBevOihaDnoj_UtieYRuMX8XfCW-WUj0SnXZAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});